version: '3'

services:
  api:
    build: ./images/api
    environment:
      - DEV_MOD=YES
    volumes:
      - ../../api:/var/www/api
    networks:
      - node
    ports:
      - "3333:3333"
      - '9229:9229'

networks:
  node:
    ipam:
      config:
        - subnet: 172.30.0.0/24
